### ISSUE TITLE
Make gradle throw an error if the jdk is not java 8.

### ISSUE THREAD

**Issue by Nucleria** [NOVA-Team/NOVA-Wrapper-MC#31]
Having an issue using 'gradle setupDecompWorkspace eclipse' inside of the NOVA-Wrapper-MC folder.

Pastebin stack trace: http://pastebin.com/h3ecDnsj

Thanks for any help you can give!

**Comment by RX14** [comment]
Update the installed jdk to version 1.8 If that doesn't fix it, try uninstalling all other jdk versions.

**Comment by RX14** [comment]
I should really make this a more descriptive error..

**Comment by Nucleria** [comment]
Thanks. i thought I had done that, but I'll check and try again.

**Comment by RX14** [comment]
Yeah I've only ever seen this error if jdk 1.8 is not installed, or more likely gradle has selected the wrong jdk. It's not very smart :/

**Comment by RX14** [comment]
If you want more support faster, head to #NovaAPI on espernet, there is almost always someone around to help.

**Comment by Nucleria** [comment]
Okay, thanks.

**Comment by RX14** [comment]
Fixed in NOVA-Team/NOVA-Gradle@c4d6425b
