### ISSUE TITLE
Obfuscation error (?) in dev environment using NOVA Gradle

### ISSUE THREAD

**Issue by Dynious** [NOVA-Team/NOVA-Wrapper-MC#43]
When setting up a new dev environment using NOVA Gradle running the 1.8 or 1.7 client instance will result in the following error (this is without the new NOVA mod sources):
http://pastebin.com/H6EKLJqz
When NOVA Mod sources are added the following error happens:
http://pastebin.com/XCUUgwsC

Tested in IntelliJ on two separate Windows machines.

**Comment by Dynious** [comment]
Woot, I can finally run MC in my dev env now! Thanks for the fix!

**Comment by RX14** [comment]
derp forgot to close this
