### ISSUE TITLE
Separate 1.7 and 1.8?

### ISSUE THREAD

**Issue by anti344** [NOVA-Team/NOVA-Wrapper-MC#50]
Idk how you doing stuff, need to login back to IRC maybe, but what your thoughts on splitting 1.7 and 1.8 wrappers into different repos?

**Comment by calclavia** [comment]
No. That's what Gradle subprojects are for.

**Comment by anti344** [comment]
Ok, thanks for your answer.
Really shold've asked this on IRC, feel stupid now =)
